Updated Dutch translation
SoongNoonien/plattenalbum pull request #159
Opened 2024-11-13 09:55 UTC by Vistaus

🙂

2024-11-13 19:03 UTC, SoongNoonien requested changes
Hi! Thanks for the update. You accidentally miss formatted your email address. I've added a suggestion to fix that. I'll also request a review from the last translator to see if he wants to say something to the changes you made.

2024-11-13 19:03 UTC, SoongNoonien commented on po/nl.po
> +"Heimen Stoffels\n"
```suggestion
"Heimen Stoffels <vistausss@fastmail.com>"
```

2024-11-13 19:04 UTC, Vistaus commented on po/nl.po
> +"vistausss@fastmail.com"
Thanks!

2024-11-13 19:05 UTC, SoongNoonien commented
Ok, apparently I can request a review from @rien333. Hopefully he sees this ping.

2024-11-13 22:06 UTC, SoongNoonien commented on po/nl.po
> +"vistausss@fastmail.com"
It's still there ;-)

2024-11-14 14:04 UTC, rien333 reviewed
Basically good to merge. My feedback is 90% nitpicky stuff that people are never going to agree on anyway. 

 This translation clearly favors more germanic/tradional dutch variants of (technical) terms, while mine favors more anglicized variants, since the latter are more popular in everyday speech, especially in tech circles. Either works, but I wonder what other apps do here.

2024-11-14 14:06 UTC, rien333 commented on po/nl.po
> +msgstr "Verzameling doorzoeken"
De Duitse vertaling hier is trouwens wel "Sammlung", dus oh well

2024-11-14 16:26 UTC, SoongNoonien commented
My Dutch isn't very good but maybe you can find some general guidance about Dutch translations for gnome apps [here](https://wiki.gnome.org/GnomeNederlands).

2024-12-10 17:02 UTC, SoongNoonien commented
Ping? @Vistaus

2025-03-26 23:00 UTC, SoongNoonien commented
Ok, @rien333 are you interested in taking this over?

2025-03-27 12:41 UTC, rien333 commented
Yes! I'll try and craft a PR based on this one next week.

2025-05-05 11:37 UTC, closed without merging